import { Urbanist } from "next/font/google";
import "./globals.css";


const urbanist = Urbanist({ subsets: ["latin"] });

export const metadata = {
  title: "Home - Innovative Smartmandu",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={urbanist.className}>
        <div className="font-urbanist">
            {children}
          </div>
      </body>
    </html>
  );
}
